### ISSUE TITLE
backlight control

### ISSUE THREAD

**Issue by uid4oe** [Rashed97/msi-gs60-hackintosh#2]
hey, apart from backlighting everything works for high sierra 10.13.5 , I don't know what I do wrong but tried everything and cant make it work any help is very much appreciated

**Comment by AutinMitra** [comment]
This is because the kexts in this repo are using VoodooPS2, which doesn't accommodate for ELAN touchpad/keyboards (such as that in the GS60). To fix this, remove VoodoPS2 and install appleSmartTouchpad.kext (or whatever it is named) from here: [https://osxlatitude.com/forums/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/](url). This will also allow you to change the keyboard color too, which you can do with my fork of msi-keyboard-gui: [https://github.com/AutinMitra/msi-keyboard-gui](msi-keyboard-gui)

**Comment by py00oe** [comment]
hey man, thanks for the quick replay, it turns out I deleted AppleBacklightExpert.kext that was the issue there is nothing wrong with your config, I so happy everything sorted out, one little thing though for USB injection there are some ports that are not used but not disabled aswell did you leave them like that intentionally or didnt bother since doesn't affect anything..

**Comment by py00oe** [comment]
++
i will try to install your keyboard gui and report back..
